name: daro_flutter
description: Daro Flutter SDK - A simple hello world package
version: 1.0.0
homepage: https://github.com/delightroom/daro-flutter-sdk
repository: https://github.com/delightroom/daro-flutter-sdk

environment:
  sdk: ^3.5.0
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: so.daro.flutter
        pluginClass: DaroFlutterPlugin
      ios:
        pluginClass: DaroFlutterPlugin
